export const keywordsMap = new Map([
    ["DOGEFATHER", "DOGEFATHER"],
    ["DOGE FATHER", "DOGEFATHER"],
    ["DOGE-FATHER", "DOGEFATHER"],
    ["ASTERIOD", "YR4"],
    ["ASTEROID", "YR4"],
    ["YR4", "YR4"],
    ["HIT EARTH", "YR4"],
    ["KEKIUS MAXIMUS", "KEKIUS MAXIMUS"],
    ["KEKIUS", "KEKIUS"],
    ["MAXIMUS", "MAXIMUS"],
    ["BIGBALLS", "BIGBALLS"],
    ["BIG BALLS", "BIGBALLS"],
    ["BIGBALL", "BIGBALL"],
    ["BIG BALL", "BIG BALL"],
    ["BIG BOLZ", "BIG BOLZ"],
    ["BIGBOLZ", "BIGBOLZ"],
    ["WHITE HOUSE TECH SUPPORT", "WHITE HOUSE TECH SUPPORT"],
    ["TECH SUPPORT", "TECH SUPPORT"],
    ["DOGE TO MARS", "DOGELON MARS"],
    ["DOGE ON MARS", "DOGELON MARS"],
    ["GROK 4", "GROK 4"],
    ["GROK-4", "GROK 4"],
    ["GROK4", "GROK 4"],
    ["GROK 5", "GROK 5"],
    ["GROK-5", "GROK 5"],
    ["GROK5", "GROK 5"],
    ["GROK 6", "GROK 6"],
    ["GROK-6", "GROK 6"],
    ["GROK6", "GROK 6"],
    ["GROK 7", "GROK 7"],
    ["GROK-7", "GROK 7"],
    ["GROK7", "GROK 7"],
    ["GROK 8", "GROK 8"],
    ["GROK-8", "GROK 8"],
    ["GROK8", "GROK 8"],
    ["GROK 9", "GROK 9"],
    ["GROK-9", "GROK 9"],
    ["GROK9", "GROK 9"],
    ["GROK 10", "GROK 10"],
    ["GROK-10", "GROK 10"],
    ["GROK10", "GROK 10"],
    ["GROK 11", "GROK 11"],
    ["GROK-11", "GROK 11"],
    ["GROK11", "GROK 11"],
    ["GROK 12", "GROK 12"],
    ["GROK-12", "GROK 12"],
    ["GROK12", "GROK 12"],
    ["GROK 2025", "GROK 2025"],
    ["GROK-2025", "GROK 2025"],
    ["GROK2025", "GROK 2025"],
    ["GROK 2026", "GROK 2026"],
    ["GROK-2026", "GROK 2026"],
    ["GROK2026", "GROK 2026"],
    ["HARY BOLZ", "HARRY BOLZ"],
    ["HARRY BOLZ", "HARRY BOLZ"],
    ["HAIRY BALLS", "HAIRY BALLS"],
    ["HAIRY BALL", "HAIRY BALL"],
    ["HARRYBOLZ", "HARRY BOLZ"],
    ["MUSK IT", "MUSK IT"],
    ["TERMINUS", "TERMINUS"],
    ["CATALORIAN", "CATALORIAN"],
    ["FATALISMFTW", "FATALISMFTW"],
    ["FATALISM FTW", "FATALISMFTW"],
    ["SHRUBIUS", "SHRUBIUS MAXIMUS"],
    ["ELAWN MOOSK", "ELAWN MOOSK"]
]);